apiVersion: v2
appVersion: "3.0.0"
description: A Helm chart for NetScaler k8s node controller
home: https://www.cloud.com
icon: https://raw.githubusercontent.com/netscaler/netscaler-helm-charts/gh-pages/netscaler.png 
maintainers:
- email: apoorva.kamath@citrix.com
  name: apoorva-05
name: netscaler-node-controller
sources:
- https://github.com/netscaler/netscaler-k8s-node-controller
version: 3.0.0
