#>>>adm-agent-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "adm-agent.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "adm-agent.fullname" . }}-core
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 4000Mi
      name: cpu
      target:
        type: Utilization
        averageValue: 1000m
#<<<adm-agent-hpa.yaml