apiVersion: v2
appVersion: "1.0.0"
description: A Helm chart for deploying all Citrix Cloud Native products 
name: citrix-cloud-native
version: 1.0.0
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
home: https://www.citrix.com
sources:
- https://github.com/citrix/
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@citrix.com
- name: subashd
  email: subash.dangol@citrix.com
dependencies:
  - name: citrix-ingress-controller
    version: "1.12.2"
    condition: cic.enabled
    alias: cic
  - name: citrix-cpx-with-ingress-controller
    version: "1.12.2"
    condition: cpx.enabled
    alias: cpx
  - name: citrix-multi-cluster-ingress-controller
    version: "1.12.2"
    condition: mcIngress.enabled
    alias: mcIngress
  - name: citrix-node-controller
    version: "2.1.0"
    condition: cnc.enabled
    alias: cnc
  - name: citrix-observability-exporter
    version: "1.2.001"
    condition: coe.enabled
    alias: coe
  - name: citrix-ipam-controller
    version: "0.0.1"
    condition: ipam.enabled
    alias: ipam
  - name: citrix-adc-istio-ingress-gateway
    version: "1.6.4"
    condition: iaIngress.enabled
    alias: iaIngress
  - name: citrix-cpx-istio-sidecar-injector
    version: "1.6.4"
    condition: iaSidecar.enabled
    alias: iaSidecar
  - name: citrix-adc-istio-egress-gateway
    version: "1.6.4"
    condition: iaEgress.enabled
    alias: iaEgress
