kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "citrix-ipam-controller.serviceAccountName" . }}
rules:
- apiGroups:
  - citrix.com
  resources:
  - vips
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "citrix-ipam-controller.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "citrix-ipam-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "citrix-ipam-controller.serviceAccountName" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "citrix-ipam-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "citrix-ipam-controller.labels" . | nindent 4 }}
