{
 "title": "ADC Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "adc_ip",
    "label": "ADC: ",
    "query": "label_values(cpu_use{Schema=\"netscaler\"},sysId)"
   },
   {
    "name": "instance",
    "label": "COE Instance",
    "query": "label_values(lstreamcpp_counters_lstrmcppd_cur_clients,instance)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "name",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "application",
    "label": "Vserver",
    "query": "label_values(vsvr_active_svcs,EntityName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress Gateway Citrix ADC Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_cs_hits_total",
     "legendFormat": "CS Vserver {{citrixadc_cs_name}}"
    }
   ]
  },
  {
   "title": "Sidecar CPX stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vsvr_tot_Hits{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Citrix ADC Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "ADC CPU use",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_use{sysId=\"$adc_ip\", instance=\"$instance\"}/10"
    }
   ]
  },
  {
   "title": "ADC Memory Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_tot_available{Schema=\"netscaler\", sysId=\"$adc_ip\", instance=\"$instance\"} + mem_cur_freesize_actual{Schema=\"netscaler\", sysId=\"$adc_ip\", instance=\"$instance\"}",
     "legendFormat": "Total Memory "
    },
    {
     "expr": "mem_cur_freesize{Schema=\"netscaler\", sysId=\"$adc_ip\" }",
     "legendFormat": "Free Memory "
    },
    {
     "expr": "mem_cur_usedsize{Schema=\"netscaler\", sysId=\"$adc_ip\", instance=\"$instance\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "mem_cur_allocsize{EntityName=\"LOGSTREAM\", sysId=\"$adc_ip\", instance=\"$instance\"}",
     "legendFormat": "Logstream Module"
    }
   ]
  },
  {
   "title": "NIC Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(nic_err_dropped_pkts{instance=\"$instance\", sysId=\"$adc_ip\"}[60s])"
    }
   ]
  },
  {
   "title": "TCP resets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(tcp_err_rst{instance=\"$instance\", sysId=\"$adc_ip\"}[60s])"
    }
   ]
  },
  {
   "title": "Current client connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "si_cur_Clients", "legendFormat": "Vserver : {{EntityName}}" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cc_cpu_use{sysId=\"$adc_ip\", instance=\"$instance\"}/10",
     "legendFormat": "CPU: {{EntityName}}"
    }
   ]
  },
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "LB Vserver State",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "si_cur_state{Schema=\"vserver_lb\", sysId=\"$adc_ip\", instance=\"$instance\"}",
     "legendFormat": "{{EntityName}}"
    }
   ]
  },
  {
   "title": "CS Vserver State",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "si_cur_state{Schema=\"vserver_cs\", sysId=\"$adc_ip\", instance=\"$instance\"}",
     "legendFormat": "{{EntityName}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "si_cur_state{Schema=\"server_svc_cfg\", sysId=\"$adc_ip\", instance=\"$instance\"}",
     "legendFormat": "{{EntityName}}"
    }
   ]
  },
  {
   "title": "ServiceGroup Status",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 15, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "si_cur_state{Schema=\"server_serviceGroup\", sysId=\"$adc_ip\", instance=\"$instance\"}",
     "legendFormat": "{{EntityName}}"
    }
   ]
  },
  {
   "title": "HTTP REQ/SEC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(vsvr_tot_Hits{EntityName=\"$application\", sysId=\"$adc_ip\", instance=\"$instance\"}[60s])",
     "legendFormat": "Vserver : {{EntityName}}"
    }
   ]
  },
  { "title": "Citrix Observability Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "HTTP Request Processed on COE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_http_reqs_done{instance=\"$instance\"} [60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Anomalous Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_anomalous_trans_recvd {instance=\"$instance\"} [60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "COE errors",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "ulfd_global_counters_ulfd_err_max_logconsumer_exceeded{instance=\"$instance\"}",
     "legendFormat": "Error Max PE connections"
    },
    {
     "expr": "ulfd_global_counters_ulfd_err_logconsumer_conn_rate_exceeded {instance=\"$instance\"}",
     "legendFormat": "Max TCP connections"
    },
    {
     "expr": "ulfd_global_counters_ulfd_err_page_no_buf {instance=\"$instance\"}",
     "legendFormat": "Unable to Send data"
    },
    {
     "expr": "ulfd_global_counters_ulfd_err_pages_dropped {instance=\"$instance\"}",
     "legendFormat": "Dropping data"
    },
    {
     "expr": "ulfd_global_counters_ulfd_err_max_shm_exceeded{instance=\"$instance\"} ",
     "legendFormat": "Shared memory limit exceded"
    },
    {
     "expr": "lstreamcpp_counters_lstrmcppd_err_kafka_server_info {instance=\"$instance\"}",
     "legendFormat": "err_kafka_server_info"
    },
    {
     "expr": "lstreamcpp_counters_lstrmcppd_err_avro_server_connect{instance=\"$instance\"}",
     "legendFormat": "Avro Server Connection failed"
    }
   ]
  },
  {
   "title": "Kafka Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upload Health",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "lstreamcpp_counters_lstrmcppd_err_kafka_file_conns_freed{instance=\"$instance\"}",
       "legendFormat": "err_kafka_file_conns_freed"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_err_kafka_meta_conns_freed{instance=\"$instance\"}",
       "legendFormat": "err_kafka_meta_conns_freed"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_err_kafka_part_leader{instance=\"$instance\"}",
       "legendFormat": "err_kafka_part_leader"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_err_kafka_pushfile {instance=\"$instance\"}",
       "legendFormat": "err_kafka_pushfile"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_err_kafka_pushfiletopic_notpresent{instance=\"$instance\"} ",
       "legendFormat": "err_kafka_pushfiletopic_notpresent"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_err_kafka_server_info {instance=\"$instance\"}",
       "legendFormat": "err_kafka_server_info"
      }
     ]
    },
    {
     "title": "Upload Stats",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile {instance=\"$instance\"}",
       "legendFormat": "pushfile"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile_succ {instance=\"$instance\"}",
       "legendFormat": "pushfile_succ"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile_removed {instance=\"$instance\"}",
       "legendFormat": "pushfile_removed"
      },
      {
       "expr": "lstreamcpp_counters_lstrmcppd_tot_avrofile_processed {instance=\"$instance\"}",
       "legendFormat": "avrofile_processed"
      },
      {
       "expr": "lstrmcppd_tot_avro_server_data_uploadmsg{instance=\"$instance\"}",
       "legendFormat": "Avro Upload"
      },
      {
       "expr": "lstrmcppd_tot_avro_server_resp_success{instance=\"$instance\"}",
       "legendFormat": "Avro Success"
      }
     ]
    },
    {
     "title": "Data Push to Kafka",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile_sz{instance=\"$instance\"}[60s])",
       "legendFormat": "Push-file size"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machine Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 2, "x": 12, "y": 36 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "singlestat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 36 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "singlestat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 2, "x": 12, "y": 38 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 4, "x": 14, "y": 38 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bps", "label": "bits out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "bytes", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    }
   ]
  }
 ]
}