apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "citrix-k8s-node-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "citrix-k8s-node-controller.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "citrix-k8s-node-controller.selectorLabels" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "citrix-k8s-node-controller.selectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: {{ include "citrix-k8s-node-controller.serviceAccountName" . }}
      {{- if .Values.deploymentTolerations }}
      tolerations:
      {{- range  .Values.deploymentTolerations }}
      - key: {{ .key }}
        operator: {{ .operator }}
        effect: {{ .effect }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ include "citrix-k8s-node-controller.name" . }}
        image: "{{ tpl .Values.image . }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: EULA
          value: {{ required "Please set license.accept=yes for accepting NetScaler License" .Values.license.accept | quote }}
        - name: NS_IP
          value: {{ required "Provide NetScaler VPX/MPX IP" .Values.nsIP | quote }}
        - name: NS_USER
          valueFrom:
            secretKeyRef:
              name: {{ required "Please provide secret for NetScaler credential" .Values.adcCredentialSecret }}
              key: username
        - name: NS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ required "Please provide secret for NetScaler credential" .Values.adcCredentialSecret }}
              key: password
        - name: NETWORK
          value: {{ required "Please provide network for VTEP overlay" .Values.network | quote }}
        - name: REMOTE_VTEPIP
          value: {{ required "Please provide NetScaler VPX/MPX SNIP" .Values.vtepIP | quote }}
        - name: VNID
          value: {{ required "Pleave provide VXLAN ID" .Values.vxlan.id | quote }}
        - name: VXLAN_PORT
          value: {{ required "Provide provide VXLAN port" .Values.vxlan.port | quote }}
        - name: CNI_TYPE
          value: {{ required "Provide CNI Type in cluster" .Values.cniType | quote }}
{{- if .Values.dsrIPRange }}
        - name: "DSR_IP_RANGE"
          value: {{ .Values.dsrIPRange | quote }}
{{- end }}
{{- if .Values.clusterName }}
        - name: "CLUSTER_NAME"
          value: {{ .Values.clusterName | quote }}
{{- end }}
{{- if .Values.cncRouterImage }}
        - name: "CNC_ROUTER_IMAGE"
          value: {{ .Values.cncRouterImage | quote }}
{{- end }}
        - name: "CNC_ROUTER_NAME"
          value: {{ include "citrix-k8s-node-controller.cncRouterName" . }} 
        - name: "CNC_CONFIGMAP"
          value: {{ include "citrix-k8s-node-controller.cncConfigMap" . }}
