kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "citrix-k8s-node-controller.serviceAccountName" . }} 
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: ["*"]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["*"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts", "clusterroles", "clusterrolebindings", "namespaces"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["*"]
    resources: ["serviceaccounts", "clusterroles", "clusterrolebindings", "namespaces"]
    verbs: ["get", "list", "create", "delete"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "citrix-k8s-node-controller.serviceAccountName" . }}
  labels:
    {{- include "citrix-k8s-node-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "citrix-k8s-node-controller.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "citrix-k8s-node-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
apiVersion: rbac.authorization.k8s.io/v1

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "citrix-k8s-node-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "citrix-k8s-node-controller.labels" . | nindent 4 }}

---
