apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: citrix-egressgateway
spec:
  selector:
    app: citrix-egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: citrix-egressgateway-for-cnn
spec:
  host: citrix-adc-istio-egress-gateway-citrix-egress-svc.citrix-system.svc.cluster.local #Note: Service name (Host) is dependent on the helm-chart release name. Use correct service name here.
  subsets:
  - name: cnn
