{{- if .Values.cpxConfig.loginCredentials.mount }}
{{- if not .Values.cpxConfig.loginCredentials.useExisting }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.cpxConfig.loginCredentials.secretName }}
type: Opaque
data:
  username: {{ .Values.cpxConfig.loginCredentials.username | b64enc }}
  password: {{ .Values.cpxConfig.loginCredentials.password | b64enc }}
{{- end }}
{{- end }}