apiVersion: v2
name: netscaler-ipam-controller
description: A Helm chart for NetScaler IPAM Controller which automatically allocate an IP address to the service of type LoadBalancer.
version: 2.1.2
appVersion: "2.1.2"
type: application
icon: https://raw.githubusercontent.com/netscaler/netscaler-helm-charts/gh-pages/netscaler.png
home: https://www.cloud.com
sources:
- https://github.com/netscaler/netscaler-k8s-ingress-controller
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@cloud.com
  
