apiVersion: v2
appVersion: "3.0.5"
kubeVersion: ">=v1.24.0-0"
description: A Helm chart for NetScaler Ingress Controller configuring MPX/VPX.
name: netscaler-ingress-controller
version: 3.0.5
icon: https://raw.githubusercontent.com/netscaler/netscaler-helm-charts/gh-pages/netscaler.png
home: https://www.netscaler.com
sources:
- https://github.com/netscaler/netscaler-k8s-ingress-controller
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@cloud.com
- name: subashd
  email: subash.dangol@cloud.com
